trigger:
  - none

pool:
  vmImage: windows-latest

variables:
  advancedsecurity.codeql.querysuite: security-extended
  advancedsecurity.submittoadvancedsecurity: true
  

steps: 
  - task: AdvancedSecurity-Codeql-Init@1
    inputs:
      languages: 'csharp'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      
  - task: AdvancedSecurity-Dependency-Scanning@1

  - task: AdvancedSecurity-Codeql-Autobuild@1

  - task: AdvancedSecurity-Codeql-Analyze@1
  
  - task: AdvancedSecurity-Publish@1 

  - task: MicrosoftSecurityDevOps@1
    inputs:
      command: 'run'
